#!/bin/bash

set -e

source ".common_funcs"

remote="${REMOTE:=origin}"
[[ -n "$(git remote | grep ${remote})" ]] || ( message ${red} "Unable to find remote ${remote}" && exit 255 )

CUR_BRANCH=$(git rev-parse --abbrev-ref HEAD)

pr_id="$1"

mess "Fetching Pull Request: ${pr_id}"
git fetch ${remote} pull/${pr_id}/head:PR-${pr_id}

mess "Checking out branch: PR-${pr_id}"
git checkout PR-${pr_id}
